name: wyatt
description: "When You Are There, Then ..."
homepage: https://wyatt.lttl.dev
repository: https://github.com/m5lk3n/wyatt
publish_to: 'none'

version: 0.1.5+6

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.4
  package_info_plus: ^8.1.3
  http: ^1.3.0
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.3
  restart_app: ^1.3.2
  google_maps_flutter: ^2.10.0
  location: ^8.0.0
  geocoding: ^3.0.0
  google_map_dynamic_key: ^1.0.1
  flutter_datetime_picker_plus: ^2.2.0
  intl: ^0.20.1
  haversine_distance: ^1.2.1
  permission_handler: ^11.3.1
  internet_connection_checker_plus: ^2.7.0
  get_storage: ^2.1.1
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000
  shared_preferences: ^2.3.5
  flutter_local_notifications: ^18.0.1
  geolocator: ^13.0.2
  timezone: ^0.10.0
  logging: ^1.3.0
  path_provider: ^2.1.5
  confirm_dialog: ^1.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  version_bmp: ^1.2.2

flutter:

  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/icon/icon-small.png
    - assets/icon/icon-medium.png
    - assets/images/logo.png
    - assets/images/appbar-bg.jpeg

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"